version: '3.8'

services:
  backend:
    build: ./backend
    networks:
      - web_gateway
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./frontend:/frontend

    environment:
      - PORT=5000
      - DB_HOST=resume-db-1
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=resume_db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - web_gateway

networks:
  web_gateway:
    external: true
